"use client";

import { useEffect, useRef, useState } from "react";

/**
 * URL-first onboarding wizard for /geo — mirrors Peec AI's onboarding flow, verified by the
 * user directly against their own site (pnc.com.tr) and documented screen-by-screen. Core
 * principle: the user only ever types a URL, every other screen's content is generated by a
 * real LLM call that's already kicked off in the background while the previous screen is
 * still being read, so there's effectively no "waiting" screen between steps. All calls
 * (lib/brand-discovery.ts, lib/topic-generator.ts, lib/prompt-suggestions.ts's
 * generateTopicGroundedPrompts) are real — demo-mode fallbacks are clearly labeled, same
 * convention as the rest of the app.
 *
 * Deliberately NOT replicated from the reference flow: a literal map widget for "target
 * market" (a free-text field does the same job without a fake-looking pin on an unreal map),
 * a timezone selector (no feature in this app does anything with it, and adding an inert
 * control would be exactly the kind of fake affordance the app's no-fabrication principle
 * argues against), and the final "choose your plan" paywall screen (Epicsem has no billing
 * system yet — see lib/plans.ts).
 *
 * Chain: step "url" kicks off /api/geo/discover; the moment that resolves, "profile" renders
 * AND /api/geo/discover-topics fires in the background; the moment topics resolve,
 * /api/geo/discover-prompts fires for ALL candidate topics (not just the ones the user ends
 * up keeping) so by "topics"→"prompts" there's no wait regardless of selection.
 *
 * Known limitation surfaced by the user's own test: LLM-suggested competitors can be wrong
 * (Peec AI itself suggested ERP vendors — Logo, Mikro, Nebim, Uyumsoft — as competitors for
 * a digital marketing agency). That's why competitors are always editable/removable with an
 * explicit caution note, never presented as verified fact.
 */

interface BrandRow {
  name: string;
  domain: string;
}

interface Topic {
  topic: string;
  why: string;
}

interface TopicPrompt {
  topic: string;
  text: string;
  branded: boolean;
}

interface Persona {
  name: string;
  description: string;
  percentage: number;
}

type Step = "url" | "profile" | "market" | "audience" | "topics" | "prompts" | "running";

interface Props {
  onComplete: (brand: BrandRow, competitors: BrandRow[], promptsText: string) => void;
  onClose: () => void;
  /** True while the parent is actually running the real GEO test the wizard just handed
   * off to — drives the "running" step's animation and tells the wizard when to close. */
  running: boolean;
}

const inputClass = "rounded-lg bg-muted border border-border px-3 py-2 text-sm outline-none focus:border-accent w-full";
const ENGINE_BADGES = ["GPT", "Claude", "Gemini", "PPX", "DeepSeek", "Grok"];

function TagEditor({ tags, onChange, placeholder }: { tags: string[]; onChange: (next: string[]) => void; placeholder: string }) {
  const [draft, setDraft] = useState("");
  function add() {
    const v = draft.trim();
    if (!v) return;
    onChange([...tags, v]);
    setDraft("");
  }
  return (
    <div className="space-y-2">
      <div className="flex flex-wrap gap-2">
        {tags.map((t, i) => (
          <span key={i} className="inline-flex items-center gap-1 rounded-full bg-muted border border-border px-3 py-1 text-xs">
            {t}
            <button type="button" onClick={() => onChange(tags.filter((_, idx) => idx !== i))} className="text-ink/40 hover:text-danger">
              ✕
            </button>
          </span>
        ))}
      </div>
      <div className="flex gap-2">
        <input
          value={draft}
          onChange={(e) => setDraft(e.target.value)}
          onKeyDown={(e) => {
            if (e.key === "Enter") {
              e.preventDefault();
              add();
            }
          }}
          placeholder={placeholder}
          className={inputClass}
        />
        <button type="button" onClick={add} className="rounded-lg bg-muted border border-border px-3 text-sm hover:border-accent shrink-0">
          + Ekle
        </button>
      </div>
    </div>
  );
}

export default function OnboardingWizard({ onComplete, onClose, running }: Props) {
  const [step, setStep] = useState<Step>("url");

  const [url, setUrl] = useState("");
  const [language, setLanguage] = useState<"tr" | "en">("tr");
  const [discoverLoading, setDiscoverLoading] = useState(false);
  const [discoverError, setDiscoverError] = useState<string | null>(null);
  const [anyDemoMode, setAnyDemoMode] = useState(false);

  const [brandName, setBrandName] = useState("");
  const [brandDomain, setBrandDomain] = useState("");
  const [description, setDescription] = useState("");
  const [industry, setIndustry] = useState("");
  const [identityAdjectives, setIdentityAdjectives] = useState<string[]>([]);
  const [competitorList, setCompetitorList] = useState<BrandRow[]>([]);

  const [productTags, setProductTags] = useState<string[]>([]);
  const [targetMarket, setTargetMarket] = useState("Türkiye");

  const [personas, setPersonas] = useState<Persona[]>([]);

  const [topics, setTopics] = useState<Topic[] | null>(null);
  const [topicsLoading, setTopicsLoading] = useState(false);
  const [topicsError, setTopicsError] = useState<string | null>(null);
  const [selectedTopics, setSelectedTopics] = useState<Set<string>>(new Set());

  const [prompts, setPrompts] = useState<TopicPrompt[] | null>(null);
  const [promptsLoading, setPromptsLoading] = useState(false);
  const [promptsError, setPromptsError] = useState<string | null>(null);
  const [checkedPrompts, setCheckedPrompts] = useState<Set<number>>(new Set());

  const promptsFetchedForRef = useRef<string | null>(null);
  const hasStartedRunningRef = useRef(false);
  const runningTimeoutRef = useRef<ReturnType<typeof setTimeout> | null>(null);

  // Once the real GEO test (handed off in finish()) actually starts, watch for it to
  // finish and close the wizard — with a 25s safety timeout in case the parent's loading
  // flag never flips true at all (e.g. a validation error short-circuited before the fetch).
  useEffect(() => {
    if (step !== "running") return;
    if (running) {
      hasStartedRunningRef.current = true;
      if (runningTimeoutRef.current) clearTimeout(runningTimeoutRef.current);
    } else if (hasStartedRunningRef.current) {
      onClose();
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [running, step]);

  useEffect(() => {
    if (step !== "running") return;
    runningTimeoutRef.current = setTimeout(() => {
      if (!hasStartedRunningRef.current) onClose();
    }, 25000);
    return () => {
      if (runningTimeoutRef.current) clearTimeout(runningTimeoutRef.current);
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [step]);

  function handleUnauthorized(res: Response) {
    if (res.status === 401) {
      window.location.href = `/login?next=${encodeURIComponent(window.location.pathname)}`;
      return true;
    }
    return false;
  }

  function audienceNoteFor(list: Persona[]): string | undefined {
    if (list.length === 0) return undefined;
    return list.map((p) => `${p.name} (%${p.percentage}) — ${p.description}`).join("; ");
  }

  async function fetchPromptsForTopics(allTopics: Topic[], brand: BrandRow, competitors: BrandRow[], personaList: Persona[]) {
    const topicLabels = allTopics.map((t) => t.topic);
    const key = topicLabels.join("|");
    if (promptsFetchedForRef.current === key) return;
    promptsFetchedForRef.current = key;
    setPromptsLoading(true);
    setPromptsError(null);
    try {
      const res = await fetch("/api/geo/discover-prompts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          brand,
          competitors: competitors.filter((c) => c.name && c.domain),
          topics: topicLabels,
          audienceNote: audienceNoteFor(personaList),
          language,
        }),
      });
      if (handleUnauthorized(res)) return;
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Prompt üretimi başarısız oldu");
      setPrompts(data.prompts);
      setCheckedPrompts(new Set(data.prompts.map((_: unknown, i: number) => i)));
      if (data.demoMode) setAnyDemoMode(true);
    } catch (err) {
      setPromptsError(err instanceof Error ? err.message : "Bir şeyler ters gitti");
    } finally {
      setPromptsLoading(false);
    }
  }

  async function fetchTopicsForBrand(brand: BrandRow, ind: string, desc: string, competitors: BrandRow[], personaList: Persona[]) {
    setTopicsLoading(true);
    setTopicsError(null);
    try {
      const res = await fetch("/api/geo/discover-topics", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ brandName: brand.name, industry: ind, description: desc, language }),
      });
      if (handleUnauthorized(res)) return;
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Topic üretimi başarısız oldu");
      const list: Topic[] = data.topics;
      setTopics(list);
      setSelectedTopics(new Set(list.slice(0, 5).map((t) => t.topic)));
      if (data.demoMode) setAnyDemoMode(true);
      // Prefetch ALL topics' prompts in the background right away — don't wait for the
      // user to reach (let alone finish) the topic-selection step.
      fetchPromptsForTopics(list, brand, competitors, personaList);
    } catch (err) {
      setTopicsError(err instanceof Error ? err.message : "Bir şeyler ters gitti");
    } finally {
      setTopicsLoading(false);
    }
  }

  async function startDiscovery(e: React.FormEvent) {
    e.preventDefault();
    if (!url.trim()) return;
    setDiscoverLoading(true);
    setDiscoverError(null);
    try {
      const res = await fetch("/api/geo/discover", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: url.trim(), language }),
      });
      if (handleUnauthorized(res)) return;
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Tarama başarısız oldu");
      setBrandName(data.brand.name);
      setBrandDomain(data.brand.domain);
      setDescription(data.description);
      setIndustry(data.industry);
      setIdentityAdjectives(data.identityAdjectives ?? []);
      setProductTags(data.productTags ?? []);
      setPersonas(data.personas ?? []);
      const competitors: BrandRow[] = data.competitors.length ? data.competitors : [{ name: "", domain: "" }];
      setCompetitorList(competitors);
      if (data.demoMode) setAnyDemoMode(true);
      setStep("profile");
      // Background: start generating topics while the user reads the profile screens.
      fetchTopicsForBrand(data.brand, data.industry, data.description, competitors, data.personas ?? []);
    } catch (err) {
      setDiscoverError(err instanceof Error ? err.message : "Bir şeyler ters gitti");
    } finally {
      setDiscoverLoading(false);
    }
  }

  function updateCompetitor(i: number, field: keyof BrandRow, value: string) {
    setCompetitorList((prev) => prev.map((c, idx) => (idx === i ? { ...c, [field]: value } : c)));
  }

  function updatePersona(i: number, field: keyof Persona, value: string) {
    setPersonas((prev) =>
      prev.map((p, idx) => (idx === i ? { ...p, [field]: field === "percentage" ? Number(value) || 0 : value } : p))
    );
  }

  function normalizePersonas() {
    if (personas.length === 0) return;
    const even = Math.floor(100 / personas.length);
    setPersonas((prev) => prev.map((p, i) => ({ ...p, percentage: i === prev.length - 1 ? 100 - even * (prev.length - 1) : even })));
  }

  const personaTotal = personas.reduce((sum, p) => sum + (p.percentage || 0), 0);

  function toggleTopic(topic: string) {
    setSelectedTopics((prev) => {
      const next = new Set(prev);
      if (next.has(topic)) next.delete(topic);
      else next.add(topic);
      return next;
    });
  }

  function togglePrompt(i: number) {
    setCheckedPrompts((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });
  }

  function finish() {
    const brand = { name: brandName.trim(), domain: brandDomain.trim() };
    const competitors = competitorList.filter((c) => c.name.trim() && c.domain.trim());
    const chosen = (prompts ?? []).filter((_, i) => checkedPrompts.has(i));
    const promptsText = chosen.map((p) => `${p.topic}: ${p.text}`).join("\n");
    setStep("running");
    onComplete(brand, competitors, promptsText);
  }

  const visiblePrompts = (prompts ?? []).filter((p) => selectedTopics.has(p.topic));
  const promptsByTopic = (topics ?? []).map((t) => ({
    topic: t.topic,
    items: (prompts ?? []).map((p, i) => ({ ...p, i })).filter((p) => p.topic === t.topic),
  }));

  const STEP_ORDER: Step[] = ["url", "profile", "market", "audience", "topics", "prompts"];
  const stepIndex = STEP_ORDER.indexOf(step);

  return (
    <div className="card space-y-4 border-accent/30">
      <div className="flex items-center justify-between">
        <div className="flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-ink/40">
          {["URL", "Marka profili", "Ürün & pazar", "Kitle", "Topic'ler", "Promptlar"].map((label, i) => (
            <span key={label} className={i <= stepIndex && step !== "running" ? "text-accent font-semibold" : ""}>
              {i > 0 && "→ "}
              {i + 1}. {label}
            </span>
          ))}
        </div>
        {step !== "running" && (
          <button type="button" onClick={onClose} className="text-xs text-ink/40 hover:text-ink/70">
            ✕ Kapat
          </button>
        )}
      </div>

      {anyDemoMode && step !== "running" && (
        <div className="rounded-lg border border-warn/40 text-warn text-xs px-3 py-2">
          <strong>Demo modda</strong> çalışıyor — bazı adımlar gerçek bir model API anahtarı olmadan simüle edildi, açıkça işaretli.
        </div>
      )}

      {step === "url" && (
        <form onSubmit={startDiscovery} className="space-y-3">
          <h2 className="font-bold text-sm">Markanızın URL&apos;ini girin</h2>
          <p className="text-xs text-ink/50">
            Sayfanızı gerçekten tarayıp marka profilini, konu başlıklarını ve promptları sizin için otomatik üretiriz —
            siz sadece gözden geçirip onaylarsınız.
          </p>
          <div className="flex gap-3">
            <input
              value={url}
              onChange={(e) => setUrl(e.target.value)}
              placeholder="https://markaniz.com"
              required
              autoFocus
              className={inputClass}
            />
            <select value={language} onChange={(e) => setLanguage(e.target.value as "tr" | "en")} className={`${inputClass} w-auto shrink-0`}>
              <option value="tr">🇹🇷 Türkçe</option>
              <option value="en">🇬🇧 English</option>
            </select>
          </div>
          {discoverError && <p className="text-xs text-danger">{discoverError}</p>}
          <button
            type="submit"
            disabled={discoverLoading}
            className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity disabled:opacity-50"
          >
            {discoverLoading ? "Taranıyor…" : "Taramayı başlat →"}
          </button>
        </form>
      )}

      {step === "profile" && (
        <div className="space-y-3">
          <h2 className="font-bold text-sm">Marka profili</h2>
          <div className="grid grid-cols-2 gap-3">
            <input value={brandName} onChange={(e) => setBrandName(e.target.value)} placeholder="Marka adı" className={inputClass} />
            <input value={brandDomain} onChange={(e) => setBrandDomain(e.target.value)} placeholder="Domain" className={inputClass} />
          </div>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            rows={2}
            className={`${inputClass} font-mono`}
          />
          <input value={industry} onChange={(e) => setIndustry(e.target.value)} placeholder="Kategori" className={inputClass} />

          <div className="space-y-1">
            <h3 className="text-xs font-semibold text-ink/50">Marka kimliği (sıfatlar)</h3>
            <TagEditor tags={identityAdjectives} onChange={setIdentityAdjectives} placeholder="örn. güvenilir" />
          </div>

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-semibold text-ink/50">Önerilen rakipler</h3>
              <button
                type="button"
                onClick={() => setCompetitorList((c) => [...c, { name: "", domain: "" }])}
                className="text-xs text-accent hover:underline"
              >
                + Rakip ekle
              </button>
            </div>
            <p className="text-xs text-warn/90">
              ⚠️ Bu öneriler sayfa içeriğinden değil modelin genel sektör bilgisinden geliyor — yanlış olabilir (ör. bir
              dijital pazarlama ajansı için ERP yazılımı önerebilir). Mutlaka gözden geçirin, gerekirse silin/düzeltin.
            </p>
            {competitorList.map((c, i) => (
              <div key={i} className="grid grid-cols-2 gap-3">
                <input value={c.name} onChange={(e) => updateCompetitor(i, "name", e.target.value)} placeholder="Rakip adı" className={inputClass} />
                <input value={c.domain} onChange={(e) => updateCompetitor(i, "domain", e.target.value)} placeholder="rakip-domaini.com" className={inputClass} />
              </div>
            ))}
          </div>

          <button
            type="button"
            onClick={() => setStep("market")}
            className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity"
          >
            İleri →
          </button>
        </div>
      )}

      {step === "market" && (
        <div className="space-y-3">
          <h2 className="font-bold text-sm">Ürünler ve hedef pazar</h2>
          <div className="space-y-1">
            <h3 className="text-xs font-semibold text-ink/50">Ürün/hizmet etiketleri</h3>
            <TagEditor tags={productTags} onChange={setProductTags} placeholder="örn. SEO danışmanlığı" />
          </div>
          <div className="space-y-1">
            <h3 className="text-xs font-semibold text-ink/50">Hedef pazar</h3>
            <input value={targetMarket} onChange={(e) => setTargetMarket(e.target.value)} placeholder="örn. Türkiye" className={inputClass} />
          </div>
          <div className="flex gap-3">
            <button type="button" onClick={() => setStep("profile")} className="text-sm text-ink/50 hover:underline">
              ← Geri
            </button>
            <button
              type="button"
              onClick={() => setStep("audience")}
              className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity"
            >
              İleri →
            </button>
          </div>
        </div>
      )}

      {step === "audience" && (
        <div className="space-y-3">
          <h2 className="font-bold text-sm">Kitle dağılımı</h2>
          <p className="text-xs text-ink/50">
            Bu dağılım sonraki adımda üretilecek promptların üslubunu etkiler — yüzdelerin toplamı 100 olmalı.
          </p>
          {personas.map((p, i) => (
            <div key={i} className="rounded-lg border border-border p-3 space-y-2">
              <div className="flex gap-3">
                <input value={p.name} onChange={(e) => updatePersona(i, "name", e.target.value)} placeholder="Persona adı" className={inputClass} />
                <input
                  type="number"
                  min={0}
                  max={100}
                  value={p.percentage}
                  onChange={(e) => updatePersona(i, "percentage", e.target.value)}
                  className={`${inputClass} w-24 shrink-0`}
                />
              </div>
              <input value={p.description} onChange={(e) => updatePersona(i, "description", e.target.value)} placeholder="Kısa açıklama" className={inputClass} />
            </div>
          ))}
          {personas.length === 0 && <p className="text-sm text-ink/40">Bu marka için persona üretilemedi — bu adımı boş geçebilirsiniz.</p>}
          {personas.length > 0 && (
            <p className={`text-xs ${personaTotal === 100 ? "text-ink/40" : "text-danger"}`}>
              Toplam: %{personaTotal}{personaTotal !== 100 && " — 100 olmalı"}
              {personaTotal !== 100 && (
                <button type="button" onClick={normalizePersonas} className="ml-2 text-accent hover:underline">
                  Eşit böl
                </button>
              )}
            </p>
          )}
          <p className="text-xs text-ink/30">
            {topicsLoading
              ? "Konu başlıkları arka planda hazırlanıyor — devam edince hazır olacak…"
              : topics
                ? `${topics.length} konu başlığı hazır.`
                : topicsError ?? ""}
          </p>
          <div className="flex gap-3">
            <button type="button" onClick={() => setStep("market")} className="text-sm text-ink/50 hover:underline">
              ← Geri
            </button>
            <button
              type="button"
              onClick={() => setStep("topics")}
              className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity"
            >
              İleri →
            </button>
          </div>
        </div>
      )}

      {step === "topics" && (
        <div className="space-y-3">
          <h2 className="font-bold text-sm">Hangi konu başlıklarını takip edelim?</h2>
          <p className="text-xs text-ink/50">
            Markanız ve kategoriniz için üretilen {topics?.length ?? "…"} konu başlığından önceliklendirmek
            istediklerinizi seçin — her biri için promptlar arka planda zaten hazırlanıyor.
          </p>
          {topicsLoading && !topics && <p className="text-sm text-ink/40">Konu başlıkları üretiliyor…</p>}
          {topicsError && !topics && <p className="text-xs text-danger">{topicsError}</p>}
          {topics && (
            <div className="flex flex-wrap gap-2">
              {topics.map((t) => (
                <button
                  key={t.topic}
                  type="button"
                  onClick={() => toggleTopic(t.topic)}
                  title={t.why}
                  className={`rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
                    selectedTopics.has(t.topic)
                      ? "bg-accent text-white border-accent"
                      : "bg-muted border-border text-ink/60 hover:border-accent/50"
                  }`}
                >
                  {t.topic}
                </button>
              ))}
            </div>
          )}
          <p className="text-xs text-ink/30">
            {promptsLoading
              ? "Promptlar arka planda hazırlanıyor…"
              : prompts
                ? `${prompts.length} prompt hazır.`
                : promptsError ?? ""}
          </p>
          <div className="flex gap-3">
            <button type="button" onClick={() => setStep("audience")} className="text-sm text-ink/50 hover:underline">
              ← Geri
            </button>
            <button
              type="button"
              disabled={!topics || selectedTopics.size === 0 || (promptsLoading && !prompts)}
              onClick={() => setStep("prompts")}
              className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity disabled:opacity-50"
            >
              {promptsLoading && !prompts ? "Promptlar hazırlanıyor…" : "İleri →"}
            </button>
          </div>
        </div>
      )}

      {step === "prompts" && (
        <div className="space-y-3">
          <h2 className="font-bold text-sm">Promptları gözden geçirin</h2>
          <p className="text-xs text-ink/50">
            {checkedPrompts.size}/{visiblePrompts.length} prompt seçili — istemediklerinizin işaretini kaldırabilirsiniz.
          </p>
          {promptsError && !prompts && <p className="text-xs text-danger">{promptsError}</p>}
          <div className="max-h-96 overflow-y-auto space-y-2 pr-1">
            {promptsByTopic
              .filter((g) => selectedTopics.has(g.topic) && g.items.length > 0)
              .map((g, gi) => (
                <details key={g.topic} open={gi === 0} className="rounded-lg border border-border">
                  <summary className="cursor-pointer select-none px-3 py-2 text-sm font-semibold flex items-center justify-between">
                    <span>{g.topic}</span>
                    <span className="text-xs text-ink/40 font-normal">{g.items.filter((p) => checkedPrompts.has(p.i)).length}/{g.items.length}</span>
                  </summary>
                  <div className="space-y-1 px-2 pb-2">
                    {g.items.map((p) => (
                      <label key={p.i} className="flex items-start gap-2 text-sm rounded-lg hover:bg-muted px-2 py-1.5">
                        <input type="checkbox" checked={checkedPrompts.has(p.i)} onChange={() => togglePrompt(p.i)} className="mt-0.5" />
                        <span>{p.text}</span>
                      </label>
                    ))}
                  </div>
                </details>
              ))}
          </div>
          <div className="flex gap-3">
            <button type="button" onClick={() => setStep("topics")} className="text-sm text-ink/50 hover:underline">
              ← Geri
            </button>
            <button
              type="button"
              disabled={checkedPrompts.size === 0 || !brandName || !brandDomain}
              onClick={finish}
              className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity disabled:opacity-50"
            >
              Kurulumu tamamla ve testi çalıştır →
            </button>
          </div>
        </div>
      )}

      {step === "running" && (
        <div className="space-y-4 text-center py-4">
          <h2 className="font-bold text-sm">Promptlar çalıştırılıyor…</h2>
          <p className="text-xs text-ink/50">
            {checkedPrompts.size} prompt, seçtiğiniz AI motorlarına gönderiliyor — bu birkaç dakika sürebilir.
          </p>
          <div className="relative w-40 h-40 mx-auto my-4">
            <div className="absolute inset-0 flex items-center justify-center">
              <div className="rounded-full bg-ink text-white text-[10px] font-bold w-14 h-14 flex items-center justify-center text-center px-1 leading-tight">
                {brandName.slice(0, 12) || "Marka"}
              </div>
            </div>
            <div className="absolute inset-0 owz-orbit">
              {ENGINE_BADGES.map((label, i) => (
                <div
                  key={label}
                  className="absolute inset-0 flex items-start justify-center"
                  style={{ transform: `rotate(${(360 / ENGINE_BADGES.length) * i}deg)` }}
                >
                  <div className="rounded-full bg-white border border-border shadow-sm text-[9px] font-semibold w-10 h-10 flex items-center justify-center text-center">
                    {label}
                  </div>
                </div>
              ))}
            </div>
          </div>
          <style>{`
            .owz-orbit { animation: owz-spin 7s linear infinite; }
            @keyframes owz-spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }
          `}</style>
        </div>
      )}
    </div>
  );
}
