"use client";

import { useRef, useState } from "react";

/**
 * URL-first onboarding wizard for /geo — mirrors the principle behind Peec AI's onboarding
 * (per the reference card the user shared): the user only ever types a URL, every other
 * screen's content is generated by a real LLM call that's already kicked off in the
 * background while the previous screen is still being read, so there's effectively no
 * "waiting" screen between steps. All 3 calls (lib/brand-discovery.ts,
 * lib/topic-generator.ts, lib/prompt-suggestions.ts's generateTopicGroundedPrompts) are
 * real — demo-mode fallbacks are clearly labeled, same convention as the rest of the app.
 *
 * Chain: step 1 (URL) kicks off /api/geo/discover; the moment that resolves, step 2 (brand
 * profile) renders AND /api/geo/discover-topics fires in the background; the moment THAT
 * resolves, /api/geo/discover-prompts fires for ALL candidate topics (not just the ones the
 * user ends up keeping) so step 3→4 has no wait regardless of topic selection.
 */

interface BrandRow {
  name: string;
  domain: string;
}

interface Topic {
  topic: string;
  why: string;
}

interface TopicPrompt {
  topic: string;
  text: string;
  branded: boolean;
}

interface Props {
  onComplete: (brand: BrandRow, competitors: BrandRow[], promptsText: string) => void;
  onClose: () => void;
}

const inputClass = "rounded-lg bg-muted border border-border px-3 py-2 text-sm outline-none focus:border-accent w-full";

export default function OnboardingWizard({ onComplete, onClose }: Props) {
  const [step, setStep] = useState<1 | 2 | 3 | 4>(1);

  const [url, setUrl] = useState("");
  const [discoverLoading, setDiscoverLoading] = useState(false);
  const [discoverError, setDiscoverError] = useState<string | null>(null);
  const [anyDemoMode, setAnyDemoMode] = useState(false);

  const [brandName, setBrandName] = useState("");
  const [brandDomain, setBrandDomain] = useState("");
  const [description, setDescription] = useState("");
  const [industry, setIndustry] = useState("");
  const [competitorList, setCompetitorList] = useState<BrandRow[]>([]);

  const [topics, setTopics] = useState<Topic[] | null>(null);
  const [topicsLoading, setTopicsLoading] = useState(false);
  const [topicsError, setTopicsError] = useState<string | null>(null);
  const [selectedTopics, setSelectedTopics] = useState<Set<string>>(new Set());

  const [prompts, setPrompts] = useState<TopicPrompt[] | null>(null);
  const [promptsLoading, setPromptsLoading] = useState(false);
  const [promptsError, setPromptsError] = useState<string | null>(null);
  const [checkedPrompts, setCheckedPrompts] = useState<Set<number>>(new Set());

  const promptsFetchedForRef = useRef<string | null>(null);

  function handleUnauthorized(res: Response) {
    if (res.status === 401) {
      window.location.href = `/login?next=${encodeURIComponent(window.location.pathname)}`;
      return true;
    }
    return false;
  }

  async function fetchPromptsForTopics(allTopics: Topic[], brand: BrandRow, competitors: BrandRow[]) {
    const topicLabels = allTopics.map((t) => t.topic);
    const key = topicLabels.join("|");
    if (promptsFetchedForRef.current === key) return;
    promptsFetchedForRef.current = key;
    setPromptsLoading(true);
    setPromptsError(null);
    try {
      const res = await fetch("/api/geo/discover-prompts", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ brand, competitors: competitors.filter((c) => c.name && c.domain), topics: topicLabels }),
      });
      if (handleUnauthorized(res)) return;
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Prompt üretimi başarısız oldu");
      setPrompts(data.prompts);
      setCheckedPrompts(new Set(data.prompts.map((_: unknown, i: number) => i)));
      if (data.demoMode) setAnyDemoMode(true);
    } catch (err) {
      setPromptsError(err instanceof Error ? err.message : "Bir şeyler ters gitti");
    } finally {
      setPromptsLoading(false);
    }
  }

  async function fetchTopicsForBrand(brand: BrandRow, ind: string, desc: string, competitors: BrandRow[]) {
    setTopicsLoading(true);
    setTopicsError(null);
    try {
      const res = await fetch("/api/geo/discover-topics", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ brandName: brand.name, industry: ind, description: desc }),
      });
      if (handleUnauthorized(res)) return;
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Topic üretimi başarısız oldu");
      const list: Topic[] = data.topics;
      setTopics(list);
      setSelectedTopics(new Set(list.slice(0, 5).map((t) => t.topic)));
      if (data.demoMode) setAnyDemoMode(true);
      // Prefetch ALL topics' prompts in the background right away — don't wait for the
      // user to reach (let alone finish) the topic-selection step.
      fetchPromptsForTopics(list, brand, competitors);
    } catch (err) {
      setTopicsError(err instanceof Error ? err.message : "Bir şeyler ters gitti");
    } finally {
      setTopicsLoading(false);
    }
  }

  async function startDiscovery(e: React.FormEvent) {
    e.preventDefault();
    if (!url.trim()) return;
    setDiscoverLoading(true);
    setDiscoverError(null);
    try {
      const res = await fetch("/api/geo/discover", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ url: url.trim() }),
      });
      if (handleUnauthorized(res)) return;
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Tarama başarısız oldu");
      setBrandName(data.brand.name);
      setBrandDomain(data.brand.domain);
      setDescription(data.description);
      setIndustry(data.industry);
      const competitors: BrandRow[] = data.competitors.length ? data.competitors : [{ name: "", domain: "" }];
      setCompetitorList(competitors);
      if (data.demoMode) setAnyDemoMode(true);
      setStep(2);
      // Background: start generating topics while the user reads the profile screen.
      fetchTopicsForBrand(data.brand, data.industry, data.description, competitors);
    } catch (err) {
      setDiscoverError(err instanceof Error ? err.message : "Bir şeyler ters gitti");
    } finally {
      setDiscoverLoading(false);
    }
  }

  function updateCompetitor(i: number, field: keyof BrandRow, value: string) {
    setCompetitorList((prev) => prev.map((c, idx) => (idx === i ? { ...c, [field]: value } : c)));
  }

  function toggleTopic(topic: string) {
    setSelectedTopics((prev) => {
      const next = new Set(prev);
      if (next.has(topic)) next.delete(topic);
      else next.add(topic);
      return next;
    });
  }

  function togglePrompt(i: number) {
    setCheckedPrompts((prev) => {
      const next = new Set(prev);
      if (next.has(i)) next.delete(i);
      else next.add(i);
      return next;
    });
  }

  function finish() {
    const brand = { name: brandName.trim(), domain: brandDomain.trim() };
    const competitors = competitorList.filter((c) => c.name.trim() && c.domain.trim());
    const chosen = (prompts ?? []).filter((_, i) => checkedPrompts.has(i));
    const promptsText = chosen.map((p) => `${p.topic}: ${p.text}`).join("\n");
    onComplete(brand, competitors, promptsText);
  }

  const visiblePrompts = (prompts ?? []).filter((p) => selectedTopics.has(p.topic));

  return (
    <div className="card space-y-4 border-accent/30">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 text-xs text-ink/40">
          <span className={step >= 1 ? "text-accent font-semibold" : ""}>1. URL</span>
          <span>→</span>
          <span className={step >= 2 ? "text-accent font-semibold" : ""}>2. Marka profili</span>
          <span>→</span>
          <span className={step >= 3 ? "text-accent font-semibold" : ""}>3. Topic&apos;ler</span>
          <span>→</span>
          <span className={step >= 4 ? "text-accent font-semibold" : ""}>4. Promptlar</span>
        </div>
        <button type="button" onClick={onClose} className="text-xs text-ink/40 hover:text-ink/70">
          ✕ Kapat
        </button>
      </div>

      {anyDemoMode && (
        <div className="rounded-lg border border-warn/40 text-warn text-xs px-3 py-2">
          <strong>Demo modda</strong> çalışıyor — bazı adımlar gerçek bir model API anahtarı olmadan simüle edildi, açıkça işaretli.
        </div>
      )}

      {step === 1 && (
        <form onSubmit={startDiscovery} className="space-y-3">
          <h2 className="font-bold text-sm">Markanızın URL&apos;ini girin</h2>
          <p className="text-xs text-ink/50">
            Sayfanızı gerçekten tarayıp marka profilini, konu başlıklarını ve promptları sizin için otomatik üretiriz —
            siz sadece gözden geçirip onaylarsınız.
          </p>
          <input
            value={url}
            onChange={(e) => setUrl(e.target.value)}
            placeholder="https://markaniz.com"
            required
            autoFocus
            className={inputClass}
          />
          {discoverError && <p className="text-xs text-danger">{discoverError}</p>}
          <button
            type="submit"
            disabled={discoverLoading}
            className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity disabled:opacity-50"
          >
            {discoverLoading ? "Taranıyor…" : "Taramayı başlat →"}
          </button>
        </form>
      )}

      {step === 2 && (
        <div className="space-y-3">
          <h2 className="font-bold text-sm">Marka profili</h2>
          <div className="grid grid-cols-2 gap-3">
            <input value={brandName} onChange={(e) => setBrandName(e.target.value)} placeholder="Marka adı" className={inputClass} />
            <input value={brandDomain} onChange={(e) => setBrandDomain(e.target.value)} placeholder="Domain" className={inputClass} />
          </div>
          <textarea
            value={description}
            onChange={(e) => setDescription(e.target.value)}
            rows={2}
            className={`${inputClass} font-mono`}
          />
          <input value={industry} onChange={(e) => setIndustry(e.target.value)} placeholder="Kategori" className={inputClass} />

          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <h3 className="text-xs font-semibold text-ink/50">Önerilen rakipler</h3>
              <button
                type="button"
                onClick={() => setCompetitorList((c) => [...c, { name: "", domain: "" }])}
                className="text-xs text-accent hover:underline"
              >
                + Rakip ekle
              </button>
            </div>
            {competitorList.map((c, i) => (
              <div key={i} className="grid grid-cols-2 gap-3">
                <input value={c.name} onChange={(e) => updateCompetitor(i, "name", e.target.value)} placeholder="Rakip adı" className={inputClass} />
                <input value={c.domain} onChange={(e) => updateCompetitor(i, "domain", e.target.value)} placeholder="rakip-domaini.com" className={inputClass} />
              </div>
            ))}
          </div>

          <p className="text-xs text-ink/30">
            {topicsLoading
              ? "Konu başlıkları arka planda hazırlanıyor — devam edince hazır olacak…"
              : topics
                ? `${topics.length} konu başlığı hazır.`
                : topicsError
                  ? topicsError
                  : ""}
          </p>

          <button
            type="button"
            onClick={() => setStep(3)}
            className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity"
          >
            İleri →
          </button>
        </div>
      )}

      {step === 3 && (
        <div className="space-y-3">
          <h2 className="font-bold text-sm">Hangi konu başlıklarını takip edelim?</h2>
          <p className="text-xs text-ink/50">
            Markanız ve kategoriniz için üretilen {topics?.length ?? "…"} konu başlığından önceliklendirmek
            istediklerinizi seçin — her biri için promptlar arka planda zaten hazırlanıyor.
          </p>
          {topicsLoading && !topics && <p className="text-sm text-ink/40">Konu başlıkları üretiliyor…</p>}
          {topicsError && !topics && <p className="text-xs text-danger">{topicsError}</p>}
          {topics && (
            <div className="flex flex-wrap gap-2">
              {topics.map((t) => (
                <button
                  key={t.topic}
                  type="button"
                  onClick={() => toggleTopic(t.topic)}
                  title={t.why}
                  className={`rounded-full border px-3 py-1.5 text-xs font-medium transition-colors ${
                    selectedTopics.has(t.topic)
                      ? "bg-accent text-white border-accent"
                      : "bg-muted border-border text-ink/60 hover:border-accent/50"
                  }`}
                >
                  {t.topic}
                </button>
              ))}
            </div>
          )}
          <p className="text-xs text-ink/30">
            {promptsLoading
              ? "Promptlar arka planda hazırlanıyor…"
              : prompts
                ? `${prompts.length} prompt hazır.`
                : promptsError ?? ""}
          </p>
          <div className="flex gap-3">
            <button type="button" onClick={() => setStep(2)} className="text-sm text-ink/50 hover:underline">
              ← Geri
            </button>
            <button
              type="button"
              disabled={!topics || selectedTopics.size === 0 || (promptsLoading && !prompts)}
              onClick={() => setStep(4)}
              className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity disabled:opacity-50"
            >
              {promptsLoading && !prompts ? "Promptlar hazırlanıyor…" : "İleri →"}
            </button>
          </div>
        </div>
      )}

      {step === 4 && (
        <div className="space-y-3">
          <h2 className="font-bold text-sm">Promptları gözden geçirin</h2>
          <p className="text-xs text-ink/50">
            {checkedPrompts.size}/{visiblePrompts.length} prompt seçili — istemediklerinizin işaretini kaldırabilirsiniz.
          </p>
          {promptsError && !prompts && <p className="text-xs text-danger">{promptsError}</p>}
          <div className="max-h-80 overflow-y-auto space-y-1 pr-1">
            {(prompts ?? []).map((p, i) => {
              if (!selectedTopics.has(p.topic)) return null;
              return (
                <label key={i} className="flex items-start gap-2 text-sm rounded-lg hover:bg-muted px-2 py-1.5">
                  <input type="checkbox" checked={checkedPrompts.has(i)} onChange={() => togglePrompt(i)} className="mt-0.5" />
                  <span>
                    <span className="text-ink/40 text-xs">{p.topic}: </span>
                    {p.text}
                  </span>
                </label>
              );
            })}
          </div>
          <div className="flex gap-3">
            <button type="button" onClick={() => setStep(3)} className="text-sm text-ink/50 hover:underline">
              ← Geri
            </button>
            <button
              type="button"
              disabled={checkedPrompts.size === 0 || !brandName || !brandDomain}
              onClick={finish}
              className="rounded-lg bg-accent text-white px-5 py-2.5 text-sm font-bold hover:opacity-90 transition-opacity disabled:opacity-50"
            >
              Kurulumu tamamla ve testi çalıştır →
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
